---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Mushroom-Checker"
  license:
    name: "MIT"
host: "mushroom.svenkraus.de"
basePath: "/v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /mushrooms:
    get:
      tags:
      - "mushroon"
      summary: "Lists all previous predictions of mushrooms"
      operationId: "get_history"
      parameters:
      - name: "last"
        in: "query"
        description: "Display the last N predictions"
        required: false
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "An array of mushroom objects from previous predictions"
          schema:
            $ref: "#/definitions/Mushrooms"
        default:
          description: "unexpected"
          schema:
            $ref: "#/definitions/UnexpectedError"
      x-swagger-router-controller: "swagger_server.controllers.mushroon_controller"
    post:
      tags:
      - "mushroon"
      summary: "Get a new mushroom prediction"
      operationId: "predict"
      parameters: []
      responses:
        200:
          description: "the predicted mushroom object"
          schema:
            $ref: "#/definitions/Mushroom"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/UnexpectedError"
      x-swagger-router-controller: "swagger_server.controllers.mushroon_controller"
definitions:
  Mushroom:
    required:
    - "bruises"
    - "cap-color"
    - "cap-shape"
    - "cap-surface"
    - "gill-attachment"
    - "gill-color"
    - "gill-size"
    - "gill-spacing"
    - "habitat"
    - "odor"
    - "population"
    - "ring-number"
    - "ring-type"
    - "spore-print-color"
    - "stalk-color-above-ring"
    - "stalk-color-below-ring"
    - "stalk-root"
    - "stalk-shape"
    - "stalk-surface-above-ring"
    - "stalk-surface-below-ring"
    - "veil-color"
    - "veil-type"
    properties:
      class:
        type: "string"
      cap-shape:
        type: "string"
      cap-surface:
        type: "string"
      cap-color:
        type: "string"
      bruises:
        type: "string"
      odor:
        type: "string"
      gill-attachment:
        type: "string"
      gill-spacing:
        type: "string"
      gill-size:
        type: "string"
      gill-color:
        type: "string"
      stalk-shape:
        type: "string"
      stalk-root:
        type: "string"
      stalk-surface-above-ring:
        type: "string"
      stalk-surface-below-ring:
        type: "string"
      stalk-color-above-ring:
        type: "string"
      stalk-color-below-ring:
        type: "string"
      veil-type:
        type: "string"
      veil-color:
        type: "string"
      ring-number:
        type: "string"
      ring-type:
        type: "string"
      spore-print-color:
        type: "string"
      population:
        type: "string"
      habitat:
        type: "string"
    example:
      stalk-color-above-ring: "stalk-color-above-ring"
      ring-type: "ring-type"
      habitat: "habitat"
      cap-surface: "cap-surface"
      stalk-surface-below-ring: "stalk-surface-below-ring"
      stalk-shape: "stalk-shape"
      stalk-root: "stalk-root"
      odor: "odor"
      gill-attachment: "gill-attachment"
      gill-size: "gill-size"
      veil-color: "veil-color"
      ring-number: "ring-number"
      population: "population"
      bruises: "bruises"
      spore-print-color: "spore-print-color"
      stalk-color-below-ring: "stalk-color-below-ring"
      cap-shape: "cap-shape"
      gill-color: "gill-color"
      veil-type: "veil-type"
      cap-color: "cap-color"
      class: "class"
      stalk-surface-above-ring: "stalk-surface-above-ring"
      gill-spacing: "gill-spacing"
  Mushrooms:
    type: "array"
    items:
      $ref: "#/definitions/Mushroom"
  UnexpectedError:
    required:
    - "errorcode"
    - "errormessage"
    properties:
      errorcode:
        type: "integer"
        format: "int32"
      errormessage:
        type: "string"
