/**
 * Mushroom-Checker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Mushroom { 
    _class?: string;
    capShape: string;
    capSurface: string;
    capColor: string;
    bruises: string;
    odor: string;
    gillAttachment: string;
    gillSpacing: string;
    gillSize: string;
    gillColor: string;
    stalkShape: string;
    stalkRoot: string;
    stalkSurfaceAboveRing: string;
    stalkSurfaceBelowRing: string;
    stalkColorAboveRing: string;
    stalkColorBelowRing: string;
    veilType: string;
    veilColor: string;
    ringNumber: string;
    ringType: string;
    sporePrintColor: string;
    population: string;
    habitat: string;
}

